### ISSUE TITLE
Greenkeeper updating babel and babel-core packages breaks Travis CI build

### ISSUE THREAD

**Issue by kendaleiv** [d4rkr00t/generator-np#40]
See https://github.com/kendaleiv/ensure-oxford-commas/pull/3.

**Comment by d4rkr00t** [comment]
Yep, I know about it. It happens because of babel 6 breaking changes and when I tried to update babel to version 6 last time it broke on ava. 

I'll definitely try again may be latter today.

**Comment by d4rkr00t** [comment]
Fixed here https://github.com/d4rkr00t/generator-np/pull/41
